### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by emilstahl** [MalwareTech/CitrixHoneypot#3]
When running
`curl -k -I --path-as-is https://[SOME_IP]/vpn/../vpns/cfg/smb.conf` or just `curl -k -I --path-as-is https:///[SOME_IP/`

I get this reponse:
`curl: (52) Empty reply from server `

Nothing gets logged, but CitrixHoneypot outputs this traceback:

```
----------------------------------------
Exception happened during processing of request from ('[SOME_IP]', 62534)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "CitrixHoneypot.py", line 22, in __init__
    super().__init__(args, directory, kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "CitrixHoneypot.py", line 25, in do_HEAD
    self.close_connection()
TypeError: 'bool' object is not callable
```

I'm seeing this on CentOS  7.7.1908 +  Python 3.6.8 and Ubuntu 16.04.6 LTS + Python 3.5.2

**Comment by emilstahl** [comment]
My bad. HEAD it not implemented, only GET. I should have figured that before 🙄

Changing line 25 to `self.close_connection = True` closes the connection without errors.

**Comment by MalwareTech** [comment]
Fixed, thanks!
